name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: addition_test.py
      id: addition_test-py
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 50
        setup-command: ''
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        ADDITION_TEST-PY_RESULTS: "${{steps.addition_test-py.outputs.result}}"
      with:
        runners: addition_test-py
